# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='virtual',
            field=models.BooleanField(default=True, verbose_name=b'Virtualizacion'),
        ),
    ]
