# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20180524_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=b'Estado'),
        ),
        migrations.AddField(
            model_name='interface',
            name='is_asignada',
            field=models.BooleanField(default=False, verbose_name=b'Estado de Asignacion'),
        ),
        migrations.AddField(
            model_name='platform',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=b'Estado'),
        ),
    ]
