# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20180530_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='client',
        ),
    ]
