# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_remove_asignacion_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Asignacion', verbose_name=b'Asignacion')),
                ('asignacionclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.AsignacionCliente', verbose_name=b'Asignacion Cliente')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Client', verbose_name=b'Cliente')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Interface', verbose_name=b'Interface')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Platform', verbose_name=b'Plataforma')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Server', verbose_name=b'Servidor')),
            ],
        ),
    ]
